### ISSUE TITLE
SSH Server

### ISSUE THREAD

**Issue by lenary** [rubypair/rubypair#15]
So there's http://showoff.io which for the moment we could use to allow remote pairing sessions to come together on the same computer via ssh tunnels.

I was thinking we could also have something like this, where essentially we have a server that can be a tunnel host for multiple people but i'm not sure how.

At some level i know we could use the ssh keys in github, and we could have an interface where we say who we let connect to us - but i've not really thought of it any more than that. 

Weirdly, I might have to build this in Erlang because i know the libraries there are better for these sorts of shenanigans - but i'll just have to see what this idea manifests itself as.

**Comment by elight** [comment]
I'm not sure about this. Giving someone else SSH access?  Granted, this is how I pair with people.  I'm not sure that everyone else would approve.

I'd previously captured this in Tracker and now, again, here: https://github.com/rubypair/rubypair/issues/26.  Issue 26 is more focused on the general problem: we want to facilitate pairing for people.  Facilitating SSH into an individual's machine is just one solution (though similar to what I already do).

Can we close this and relocate discussion to Issue 26?

**Comment by lenary** [comment]
yeah, merge them. but please preserve both sets of comments - i have more to say!
