### ISSUE TITLE
interests not saving for add/update profile

### ISSUE THREAD

**Issue by deJaVisions** [rubypair/rubypair#28]
using firefox 6.0.2 on mac

**Comment by elight** [comment]
It's a usability issue. Tags don't get saved until you hit the "Update User" button.

**Comment by deJaVisions** [comment]
Ahh there we go, I didn't notice the "click enter after each tag" part, and it wasn't intutive to do so. We had this issue on another site (the tag entering not being intuitive), so we ended up adding , and /  as auto tag delimiters... so in other words when you enter either a , or a / or enter, it adds the tag. Just a suggestion tho, the site looks great.

**Comment by elight** [comment]
I hope the UI makes more sense now that the style has been correctly reapplied? It's supposed to resemble a textarea prompting the user to hit the submit.

**Comment by elight** [comment]
I literally just fixed the styling issue.

**Comment by deJaVisions** [comment]
Ahh yes, that feels much better, thanks!

I just tried out a clone of it on my local as my first open source clone.
Fun times, Git is so Awesome.
