### ISSUE TITLE
Tagify-css is all goofed up

### ISSUE THREAD

**Issue by elight** [rubypair/rubypair#29]
https://skitch.com/evanlight/faw31/edit-profile-rubypair

**Comment by elight** [comment]
Fixed by 41223cdf82d50870b5fb4a90f2868dc1411e0148

**Comment by lenary** [comment]
so was it really just the load order f*cking stuff up?

**Comment by elight** [comment]
No. The CSS file was removed from the directory. I added it back. Then I told Sprockets to merge it into application.css. This doesn't occur automagically; it has to be specified in the "manifest" file -- in application.css' comments.
