### ISSUE TITLE
Tools page

### ISSUE THREAD

**Issue by jimsynz** [rubypair/rubypair#51]
It should have a tools page talking about the methods and tools used for remote pairing. The reason I know this is that I don't know what tools are in use myself, so I went looking for it! :)

**Comment by lenary** [comment]
This makes a lot of sense. Maybe we need a wiki of some kind for this sort of thing.

**Comment by jimsynz** [comment]
I'd say that the overlap between people who want to remotely pair and people who use github would be almost complete, why don't we just use this project's wiki?

**Comment by elight** [comment]
Huh. Couuld've sworn that I responded to this.  Absolutely love this idea!
